version: '3.8'

services:
  postgres:
    image: postgres:16.3-alpine3.20
    container_name: postgres
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4:8.8
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - app_network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.4
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KC_HOSTNAME_STRICT_HTTPS: "false"
    ports:
      - "8081:8080"
    command:
      - start-dev
    depends_on:
      - postgres
    networks:
      - app_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  app_network: